# # Visit https://github.com/lowlighter/metrics#-documentation for full reference
# name: Metrics
# on:
#   # Schedule updates (each hour)
#   schedule: [{ cron: "0 * * * *" }]
#   # Lines below let you run workflow manually and on each commit
#   workflow_dispatch:
#   push: { branches: ["master", "main"] }
# jobs:
#   github-metrics:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#     steps:
#       - uses: lowlighter/metrics@latest
#         with:
#           # Your GitHub token
#           # The following scopes are required:
#           #  - public_access (default scope)
#           # The following additional scopes may be required:
#           #  - read:org      (for organization related metrics)
#           #  - read:user     (for user related data)
#           #  - read:packages (for some packages related data)
#           #  - repo          (optional, if you want to include private repositories)
#           token: ${{ secrets.METRICS_TOKEN }}

#           # Options
#           user: unbrain
#           template: classic
#           base: header, activity, community, repositories, metadata
#           config_timezone: Asia/Shanghai
#           plugin_isocalendar: yes
#           plugin_isocalendar_duration: half-year
#       - uses: lowlighter/metrics@latest
#         with:
#           filename: metrics.plugin.wakatime.svg
#           token: NOT_NEEDED
#           base: ""
#           plugin_wakatime_days: 7
#           plugin_wakatime: yes
#           plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
#           plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
